server:
  port: 8080
  servlet:
    context-path: /beer-test

# DATASOURCE
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/beertest?currentSchema=public}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASS:changeme}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

waypoint:
  maxDistance: ${MAX_DISTANCE:2000} # max distance in km
  maxTourSize: ${MAX_TOUR_SIZE :10000}
  closestPointLimit: ${CLOSEST_POINT_LIMIT:10}
  mostBeersLimit: ${MOST_BEERS_LIMIT:10}

aspect:
  enabled: true
