version: "3"

services:
  postgres:
    image: postgres:15.4-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: beertest
    volumes:
      - ../src/main/resources/beer-data:/tmp/
