version: "3"

services:
  postgres:
    image: postgres:15.4-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: beertest
    volumes:
      - ../src/main/resources/beer-data:/tmp/

#  beer-test-app:
#    build:
#      context: ../
#      dockerfile: ../Dockerfile
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      DATABASE_URL: jdbc:postgresql://postgres:5432/beertest?currentSchema=public
#      DB_USERNAME: DB_USERNAME:postgres
#      DB_PASS: changeme
